os: linux
language: c
compiler: gcc
sudo: false
matrix:
  include:
    - compiler: ": Complete"
      env: CONFIGURE_OPTS="--enable-tool --enable-static --enable-shared" MAKE_CHECK=1
      addons:
        apt:
            packages:
            - build-essential
            - libgcrypt11-dev
    - compiler: ": No tool/tests"
      env: CONFIGURE_OPTS="--disable-tool --enable-static --enable-shared"
      addons:
        apt:
            packages:
            - build-essential
    - compiler: ": Win32 - No tool/tests"
      env: CONFIGURE_OPTS="--disable-tool --host=i686-w64-mingw32 --enable-static --enable-shared"
      addons:
        apt:
            packages:
            - gcc-mingw-w64-i686
            - binutils-mingw-w64-i686
            - mingw-w64-dev
    - compiler: ": Win64 - No tool/tests"
      env: CONFIGURE_OPTS="--disable-tool --host=x86_64-w64-mingw32 --enable-static --enable-shared"
      addons:
        apt:
            packages:
            - gcc-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
            - mingw-w64-dev
  exclude:
    - compiler: gcc
install:
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
script:
    - unset CC
    - ./autogen.sh
    - ./configure $CONFIGURE_OPTS || tail -n 1000 config.log
    - make
    - test -z "$MAKE_CHECK" || make check
    - make install DESTDIR=$PWD/ii
    - cd ii && find
